### ISSUE TITLE
newAccount + Faucet 합치기

### ISSUE THREAD

**Issue by youjinlee-code** [nittre/ganache-transaction-daemon#10]
### TODO
- [ ] 새로운 계정을 만들면 바로 faucet을 실행한다.
- [ ] 계정 생성 후 DB에 저장한다.
- [ ] faucet 후 트랜잭션 DB에 트랜잭션 아이디, from, to, 블록넘버를 저장한다.
