### ISSUE TITLE
transaction 테이블 생성

### ISSUE THREAD

**Issue by youjinlee-code** [nittre/ganache-transaction-daemon#11]
### TODO
- [ ] Transaction 테이블 생성
- [ ] newTransaction 후 트랜잭션 데이터 저장
- [ ] daemon에서 트랜잭션 데이터 주기적으로 저장하는 코드 추가
