### ISSUE TITLE
[데몬 서버] daemon 함수 만들기

### ISSUE THREAD

**Issue by youjinlee-code** [nittre/ganache-transaction-daemon#7]
### TODO
- [x] 서버 전역에 마지막으로 읽은 블록을 변수에 저장
- [x] 그 변수에서부터 체인에 있는 최신 블록까지 가져옴
- [x] 블록 까서 트랜잭션 확인
- [x] 트랜잭션에 우리 DB에 저장된 주소가 있다면? => 바~로 확인해서 DB 업데이트

### Description
- faucet, 송금에 대해 데이터베이스를 업데이트해야함
